[package]
name = "ionpak-firmware"
version = "0.1.0"
authors = ["whitequark <whitequark@whitequark.org>"]

[dependencies]
cortex-m = "0.3.1"
cortex-m-rt = { version = "0.3.5" }

[dependencies.tm4c129x]
git = "https://github.com/m-labs/dslite2svd"
rev = "d527f3f"
features = ["rt"]

[dependencies.smoltcp]
git = "https://github.com/m-labs/smoltcp"
rev = "d03ea64"
features = []
default-features = false

[profile.release]
lto = true
debug = true
